### ISSUE TITLE
issues in make_catkin.sh 

### ISSUE THREAD

**Issue by loli11111q** [iamlab-cmu/franka-interface#21]
Hello, I have resolved the issue with the build Franka interface. I previously installed Protobuf on my computer, which may have caused conflicts. Therefore, I switched to a new system and this issue has been resolved. However, I encountered an error while building catkin again."bash ./bash_scripts/make_catkin.sh". I have successfully built 10 out of 11 packages, but the last one, franka_gazebo, was not successful. I noticed that the error message is a mismatch between the gazebo and protobuf versions. I would like to inquire about the version information of the two you are using and how I can solve this problem.

> /usr/include/gazebo-9/gazebo/msgs/joint_animation.pb.h: In member function ‘void gazebo::msgs::JointAnimation::set_allocated_model_name(std::__cxx11::string*)’:
/usr/include/gazebo-9/gazebo/msgs/joint_animation.pb.h:434:15: error: ‘struct google::protobuf::internal::ArenaStringPtr’ has no member named ‘SetAllocatedNoArena’; did you mean ‘SetAllocated’?
   model_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model_name);
               ^~~~~~~~~~~~~~~~~~~
               SetAllocated
In file included from /usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h:30:0,
                 from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:51,
                 from /usr/include/gazebo-9/gazebo/physics/Joint.hh:29,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/joint.h:10,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/controller_verifier.h:2,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/src/controller_verifier.cpp:1:
/usr/include/gazebo-9/gazebo/msgs/pid.pb.h: At global scope:
/usr/include/gazebo-9/gazebo/msgs/pid.pb.h:182:33: error: ‘InternalMetadataWithArena’ in namespace ‘google::protobuf::internal’ does not name a type
   ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/gazebo-9/gazebo/msgs/pid.pb.h: In member function ‘const google::protobuf::UnknownFieldSet& gazebo::msgs::PID::unknown_fields() const’:
/usr/include/gazebo-9/gazebo/msgs/pid.pb.h:61:47: error: no matching function for call to ‘google::protobuf::internal::InternalMetadata::unknown_fields() const’
     return _internal_metadata_.unknown_fields();
                                               ^
In file included from /usr/local/include/google/protobuf/message_lite.h:54:0,
                 from /usr/local/include/google/protobuf/any.h:38,
                 from /usr/local/include/google/protobuf/generated_message_util.h:52,
                 from /usr/include/gazebo-9/gazebo/msgs/altimeter.pb.h:24,
                 from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:7,
                 from /usr/include/gazebo-9/gazebo/physics/Joint.hh:29,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/joint.h:10,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/controller_verifier.h:2,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/src/controller_verifier.cpp:1:
/usr/local/include/google/protobuf/metadata_lite.h:141:35: note: candidate: template<class T> const T& google::protobuf::internal::InternalMetadata::unknown_fields(const T& (*)()) const
   PROTOBUF_NDEBUG_INLINE const T& unknown_fields(
                                   ^~~~~~~~~~~~~~
/usr/local/include/google/protobuf/metadata_lite.h:141:35: note:   template argument deduction/substitution failed:
In file included from /usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h:30:0,
                 from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:51,
                 from /usr/include/gazebo-9/gazebo/physics/Joint.hh:29,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/joint.h:10,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/controller_verifier.h:2,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/src/controller_verifier.cpp:1:
/usr/include/gazebo-9/gazebo/msgs/pid.pb.h:61:47: note:   candidate expects 1 argument, 0 provided
     return _internal_metadata_.unknown_fields();
                                               ^
/usr/include/gazebo-9/gazebo/msgs/pid.pb.h: In member function ‘google::protobuf::UnknownFieldSet* gazebo::msgs::PID::mutable_unknown_fields()’:
/usr/include/gazebo-9/gazebo/msgs/pid.pb.h:65:55: error: no matching function for call to ‘google::protobuf::internal::InternalMetadata::mutable_unknown_fields()’
     return _internal_metadata_.mutable_unknown_fields();
                                                       ^
In file included from /usr/local/include/google/protobuf/message_lite.h:54:0,
                 from /usr/local/include/google/protobuf/any.h:38,
                 from /usr/local/include/google/protobuf/generated_message_util.h:52,
                 from /usr/include/gazebo-9/gazebo/msgs/altimeter.pb.h:24,
                 from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:7,
                 from /usr/include/gazebo-9/gazebo/physics/Joint.hh:29,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/joint.h:10,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/controller_verifier.h:2,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/src/controller_verifier.cpp:1:
/usr/local/include/google/protobuf/metadata_lite.h:151:29: note: candidate: template<class T> T* google::protobuf::internal::InternalMetadata::mutable_unknown_fields()
   PROTOBUF_NDEBUG_INLINE T* mutable_unknown_fields() {
                             ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/google/protobuf/metadata_lite.h:151:29: note:   template argument deduction/substitution failed:
In file included from /usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h:30:0,
                 from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:51,
                 from /usr/include/gazebo-9/gazebo/physics/Joint.hh:29,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/joint.h:10,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/controller_verifier.h:2,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/src/controller_verifier.cpp:1:
/usr/include/gazebo-9/gazebo/msgs/pid.pb.h:65:55: note:   couldn't deduce template parameter ‘T’
     return _internal_metadata_.mutable_unknown_fields();
                                                       ^
In file included from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:51:0,
                 from /usr/include/gazebo-9/gazebo/physics/Joint.hh:29,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/joint.h:10,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/controller_verifier.h:2,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/src/controller_verifier.cpp:1:
/usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h: At global scope:
/usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h:183:33: error: ‘InternalMetadataWithArena’ in namespace ‘google::protobuf::internal’ does not name a type
   ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h: In member function ‘const google::protobuf::UnknownFieldSet& gazebo::msgs::JointCmd::unknown_fields() const’:
/usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h:62:47: error: no matching function for call to ‘google::protobuf::internal::InternalMetadata::unknown_fields() const’
     return _internal_metadata_.unknown_fields();
                                               ^
In file included from /usr/local/include/google/protobuf/message_lite.h:54:0,
                 from /usr/local/include/google/protobuf/any.h:38,
                 from /usr/local/include/google/protobuf/generated_message_util.h:52,
                 from /usr/include/gazebo-9/gazebo/msgs/altimeter.pb.h:24,
                 from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:7,
                 from /usr/include/gazebo-9/gazebo/physics/Joint.hh:29,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/joint.h:10,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/controller_verifier.h:2,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/src/controller_verifier.cpp:1:
/usr/local/include/google/protobuf/metadata_lite.h:141:35: note: candidate: template<class T> const T& google::protobuf::internal::InternalMetadata::unknown_fields(const T& (*)()) const
   PROTOBUF_NDEBUG_INLINE const T& unknown_fields(
                                   ^~~~~~~~~~~~~~
/usr/local/include/google/protobuf/metadata_lite.h:141:35: note:   template argument deduction/substitution failed:
In file included from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:51:0,
                 from /usr/include/gazebo-9/gazebo/physics/Joint.hh:29,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/joint.h:10,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/controller_verifier.h:2,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/src/controller_verifier.cpp:1:
/usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h:62:47: note:   candidate expects 1 argument, 0 provided
     return _internal_metadata_.unknown_fields();
                                               ^
/usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h: In member function ‘google::protobuf::UnknownFieldSet* gazebo::msgs::JointCmd::mutable_unknown_fields()’:
/usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h:66:55: error: no matching function for call to ‘google::protobuf::internal::InternalMetadata::mutable_unknown_fields()’
     return _internal_metadata_.mutable_unknown_fields();
                                                       ^
In file included from /usr/local/include/google/protobuf/message_lite.h:54:0,
                 from /usr/local/include/google/protobuf/any.h:38,
                 from /usr/local/include/google/protobuf/generated_message_util.h:52,
                 from /usr/include/gazebo-9/gazebo/msgs/altimeter.pb.h:24,
                 from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:7,
                 from /usr/include/gazebo-9/gazebo/physics/Joint.hh:29,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/joint.h:10,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/controller_verifier.h:2,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/src/controller_verifier.cpp:1:
/usr/local/include/google/protobuf/metadata_lite.h:151:29: note: candidate: template<class T> T* google::protobuf::internal::InternalMetadata::mutable_unknown_fields()
   PROTOBUF_NDEBUG_INLINE T* mutable_unknown_fields() {
                             ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/google/protobuf/metadata_lite.h:151:29: note:   template argument deduction/substitution failed:
In file included from /usr/include/gazebo-9/gazebo/msgs/MessageTypes.hh:51:0,
                 from /usr/include/gazebo-9/gazebo/physics/Joint.hh:29,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/joint.h:10,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/include/franka_gazebo/controller_verifier.h:2,
                 from /home/hhh/franka-interface/catkin_ws/src/franka_ros/franka_gazebo/src/controller_verifier.cpp:1:
/usr/include/gazebo-9/gazebo/msgs/joint_cmd.pb.h:66:55: note:   couldn't deduce template parameter ‘T’

**Comment by Taiyu-Jin** [comment]
did you solve the problem? I meet the same as yours.

**Comment by Ynao3** [comment]
你直接在makelist文件里面把gazebo编译的那部分删掉就好了，先不管gazebo。

**Comment by Taiyu-Jin** [comment]
thanks,this problem had been solved,but i meet another problem

`(franka_virtual_env) humanoid@humanoid:~/franka-interface/build$  ./franka_interface --robot_ip 172.16.0.2 --with_gripper 0 --log 0 --stop_on_error 0
IAM FrankaInterface
Will start run loop.
start run loop.
start run loop.
Did create all shared memory buffers.
Did start run loop.
Will run..
Will try to acquire lock while setting franka_interface status
Failed to get lock to update process info
`
Can i communicate with you in Wechat

**Comment by malmm1** [comment]
I am running into this error while running `bash ./bash_scripts/make_catkin.sh`. Only two packages are installed successfully. Please help us with a possible solution. Thank you.=!!

Profile:                     default
Extending:          [cached] /home/rockt/Documents/frankapy/frankapy/catkin_ws/devel:/opt/ros/noetic
Workspace:                   /home/rockt/Downloads/franka-interface/catkin_ws
----------------------------------------------------------------------------------------------------
Build Space:        [exists] /home/rockt/Downloads/franka-interface/catkin_ws/build
Devel Space:        [exists] /home/rockt/Downloads/franka-interface/catkin_ws/devel
Install Space:      [unused] /home/rockt/Downloads/franka-interface/catkin_ws/install
Log Space:          [exists] /home/rockt/Downloads/franka-interface/catkin_ws/logs
Source Space:       [exists] /home/rockt/Downloads/franka-interface/catkin_ws/src
DESTDIR:            [unused] None
----------------------------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
----------------------------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
----------------------------------------------------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
----------------------------------------------------------------------------------------------------
Workspace configuration appears valid.
----------------------------------------------------------------------------------------------------
[build] Found 11 packages in 0.0 seconds.                                                                                                                                                                 
[build] Package table is up to date.                                                                                                                                                                      
Starting  >>> franka_description                                                                                                                                                                          
Starting  >>> franka_gripper                                                                                                                                                                              
Starting  >>> franka_interface_msgs                                                                                                                                                                       
Starting  >>> franka_msgs                                                                                                                                                                                 
Finished  <<< franka_description                        [ 0.2 seconds ]                                                                                                                                   
Starting  >>> franka_visualization                                                                                                                                                                        
__________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << franka_msgs:make /home/rockt/Downloads/franka-interface/catkin_ws/logs/franka_msgs/build.make.002.log                                                                                       
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/geneus/geneus_main.py", line 136, in genmain
    pkg_map = get_pkg_map()
  File "/opt/ros/noetic/lib/python3/dist-packages/geneus/geneus_main.py", line 56, in get_pkg_map
    pkgs = packages.find_packages(ws)
  File "/home/rockt/miniconda3/envs/franka_cmu/lib/python3.6/site-packages/catkin_pkg/packages.py", line 94, in find_packages
    ignore_markers=ignore_markers)
  File "/home/rockt/miniconda3/envs/franka_cmu/lib/python3.6/site-packages/catkin_pkg/packages.py", line 156, in find_packages_allowing_duplicates
    xml, filename=filename, warnings=warnings)
  File "/home/rockt/miniconda3/envs/franka_cmu/lib/python3.6/site-packages/catkin_pkg/package.py", line 786, in parse_package_string
    raise InvalidPackage('Error(s):%s' % (''.join(['\n- %s' % e for e in errors])), filename)
catkin_pkg.package.InvalidPackage: Error(s) in package '/home/rockt/Documents/frankapy/frankapy/catkin_ws/devel/protobuf-21.8/php/ext/google/protobuf/package.xml':
Error(s):
- The manifest of package "protobuf" (with format version 1) must not contain the following tags: date, providesextension, time, dependencies, lead, notes, changelog, channel, summary, stability, extsrcrelease, contents
make[2]: *** [CMakeFiles/franka_msgs_generate_messages_eus.dir/build.make:179: /home/rockt/Downloads/franka-interface/catkin_ws/devel/.private/franka_msgs/share/roseus/ros/franka_msgs/manifest.l] Error 3
make[1]: *** [CMakeFiles/Makefile2:920: CMakeFiles/franka_msgs_generate_messages_eus.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/rockt/Downloads/franka-interface/catkin_ws/build/franka_msgs; catkin build --get-env franka_msgs | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

..........................................................................................................................................................................................................
Failed     << franka_msgs:make                          [ Exited with code 2 ]                                                                                                                            
Failed    <<< franka_msgs                               [ 1.4 seconds ]                                                                                                                                   
Abandoned <<< franka_hw                                 [ Unrelated job failed ]                                                                                                                          
Abandoned <<< franka_control                            [ Unrelated job failed ]                                                                                                                          
Abandoned <<< franka_example_controllers                [ Unrelated job failed ]                                                                                                                          
Abandoned <<< franka_gazebo                             [ Unrelated job failed ]                                                                                                                          
Abandoned <<< franka_ros                                [ Unrelated job failed ]                                                                                                                          
Abandoned <<< franka_ros_interface                      [ Unrelated job failed ]                                                                                                                          
__________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << franka_interface_msgs:make /home/rockt/Downloads/franka-interface/catkin_ws/logs/franka_interface_msgs/build.make.002.log                                                                   
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/geneus/geneus_main.py", line 136, in genmain
    pkg_map = get_pkg_map()
  File "/opt/ros/noetic/lib/python3/dist-packages/geneus/geneus_main.py", line 56, in get_pkg_map
    pkgs = packages.find_packages(ws)
  File "/home/rockt/miniconda3/envs/franka_cmu/lib/python3.6/site-packages/catkin_pkg/packages.py", line 94, in find_packages
    ignore_markers=ignore_markers)
  File "/home/rockt/miniconda3/envs/franka_cmu/lib/python3.6/site-packages/catkin_pkg/packages.py", line 156, in find_packages_allowing_duplicates
    xml, filename=filename, warnings=warnings)
  File "/home/rockt/miniconda3/envs/franka_cmu/lib/python3.6/site-packages/catkin_pkg/package.py", line 786, in parse_package_string
    raise InvalidPackage('Error(s):%s' % (''.join(['\n- %s' % e for e in errors])), filename)
catkin_pkg.package.InvalidPackage: Error(s) in package '/home/rockt/Documents/frankapy/frankapy/catkin_ws/devel/protobuf-21.8/php/ext/google/protobuf/package.xml':
Error(s):
- The manifest of package "protobuf" (with format version 1) must not contain the following tags: stability, notes, channel, lead, contents, changelog, providesextension, date, dependencies, time, extsrcrelease, summary
make[2]: *** [CMakeFiles/franka_interface_msgs_generate_messages_eus.dir/build.make:183: /home/rockt/Downloads/franka-interface/catkin_ws/devel/.private/franka_interface_msgs/share/roseus/ros/franka_interface_msgs/manifest.l] Error 3
make[1]: *** [CMakeFiles/Makefile2:1439: CMakeFiles/franka_interface_msgs_generate_messages_eus.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/rockt/Downloads/franka-interface/catkin_ws/build/franka_interface_msgs; catkin build --get-env franka_interface_msgs | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

..........................................................................................................................................................................................................
Failed     << franka_interface_msgs:make                [ Exited with code 2 ]                                                                                                                            
Failed    <<< franka_interface_msgs                     [ 1.2 seconds ]                                                                                                                                   
__________________________________________________________________________________________________________________________________________________________________________________________________________
Errors     << franka_gripper:make /home/rockt/Downloads/franka-interface/catkin_ws/logs/franka_gripper/build.make.002.log                                                                                 
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/geneus/geneus_main.py", line 136, in genmain
    pkg_map = get_pkg_map()
  File "/opt/ros/noetic/lib/python3/dist-packages/geneus/geneus_main.py", line 56, in get_pkg_map
    pkgs = packages.find_packages(ws)
  File "/home/rockt/miniconda3/envs/franka_cmu/lib/python3.6/site-packages/catkin_pkg/packages.py", line 94, in find_packages
    ignore_markers=ignore_markers)
  File "/home/rockt/miniconda3/envs/franka_cmu/lib/python3.6/site-packages/catkin_pkg/packages.py", line 156, in find_packages_allowing_duplicates
    xml, filename=filename, warnings=warnings)
  File "/home/rockt/miniconda3/envs/franka_cmu/lib/python3.6/site-packages/catkin_pkg/package.py", line 786, in parse_package_string
    raise InvalidPackage('Error(s):%s' % (''.join(['\n- %s' % e for e in errors])), filename)
catkin_pkg.package.InvalidPackage: Error(s) in package '/home/rockt/Documents/frankapy/frankapy/catkin_ws/devel/protobuf-21.8/php/ext/google/protobuf/package.xml':
Error(s):
- The manifest of package "protobuf" (with format version 1) must not contain the following tags: extsrcrelease, stability, notes, time, changelog, contents, providesextension, channel, dependencies, date, summary, lead
make[2]: *** [CMakeFiles/franka_gripper_generate_messages_eus.dir/build.make:318: /home/rockt/Downloads/franka-interface/catkin_ws/devel/.private/franka_gripper/share/roseus/ros/franka_gripper/manifest.l] Error 3
make[1]: *** [CMakeFiles/Makefile2:1014: CMakeFiles/franka_gripper_generate_messages_eus.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/rockt/Downloads/franka-interface/catkin_ws/build/franka_gripper; catkin build --get-env franka_gripper | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

..........................................................................................................................................................................................................
Failed     << franka_gripper:make                       [ Exited with code 2 ]                                                                                                                            
Failed    <<< franka_gripper                            [ 1.7 seconds ]                                                                                                                                   
Finished  <<< franka_visualization                      [ 0.3 seconds ]                                                                                                                                   
[build] Summary: 2 of 11 packages succeeded.                                                                                                                                                              
[build]   Ignored:   None.                                                                                                                                                                                
[build]   Warnings:  None.                                                                                                                                                                                
[build]   Abandoned: 6 packages were abandoned.                                                                                                                                                           
[build]   Failed:    3 packages failed.                                                                                                                                                                   
[build] Runtime: 1.9 seconds total.
